2022.02.15 add stereo nodelet
GITAI/flir_camera_driver pull request #41
Opened 2022-02-16 07:53 UTC by AkiraShibata18

- [ ] add new nodelet
- [ ] separate ConnectCb
- [ ] modify devicePoll
- [ ] separate dynamic reconfigure
- [ ] prepare camera settings for each camera
- [ ] modify diagnostics
- [ ] test on device

2022-02-17 05:09 UTC, garaemon requested changes

2022-02-17 05:09 UTC, garaemon commented on spinnaker_camera_driver/src/stereo_nodelet.cpp
> +      switch (left_state)
この部分、さすがにコピペが気になるので、left_stateとright_stateで関数に分離できますか?

イメージは
```c++
void stateHandle(State& state, ros::Subscription& sub, SpinnakerCamera& camera)
{
 switch(state)
{
  case SHUTDOWN;
    ....
}
}
```

みたいな関数にしておいて、
```c++
stateHandle(left_state, sub_left_, spinnaker_left_);
stateHandle(right_state, sub_right_, spinnaker_right_);
```

みたいに呼び出したいです

2022-02-17 05:09 UTC, garaemon commented on spinnaker_camera_driver/src/stereo_nodelet.cpp
> +        case STARTED:
この部分は、`switch(left_state)`と`switch(right_state)`の外にくくりだして、
```c++
if (left_state == STARTED && right_state == STARTED) 
{
...
}
```

みたいにできると良いと思いましたが可能そうでしょうか?

2022-02-17 11:25 UTC, AkiraShibata18 commented on spinnaker_camera_driver/src/stereo_nodelet.cpp
> +      switch (left_state)
ありがとうございます。
`stateHandle`追加してみました。一部left, rightの分岐が必要だったため`is_left` flagを使用しています。

2022-02-17 11:26 UTC, AkiraShibata18 commented on spinnaker_camera_driver/src/stereo_nodelet.cpp
> +        case STARTED:
ありがとうございます。
上記の`stateHandle`のあとでif文にしました。

2022-02-19 09:26 UTC, garaemon requested changes

2022-02-19 09:26 UTC, garaemon commented on spinnaker_camera_driver/src/stereo_nodelet.cpp
> +
この辺のfile名などUpdateしておいてもらえますか?
上のCoyrightもGITAI Japanを追加しておいてください

2022-02-21 04:24 UTC, AkiraShibata18 commented on spinnaker_camera_driver/src/stereo_nodelet.cpp
> +
ありがとうございます。追加しました。

2022-02-21 06:12 UTC, garaemon approved these changes

2022-02-21 07:41 UTC, merged